[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-dashboard"
version = "1.0.0"
description = "Advanced Financial Dashboard with Streamlit"
dependencies = [
    "streamlit>=1.28.0",
    "plotly>=5.15.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "yfinance>=0.2.18",
    "requests>=2.31.0",
    "alpha_vantage>=2.3.1",
    "python-dotenv>=1.0.0",
    "plotly-express>=0.4.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "python-dateutil>=2.8.2",
    "pytz>=2023.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]
